exports.TRANSPORT_BY_FOOT = 1
exports.TRANSPORT_BY_BUS = 2
exports.TRANSPORT_BY_CAR = 3
exports.TRANSPORT_BY_TRAIN = 4
exports.TRANSPORT_BY_PLANE = 5
exports.TRANSPORT_BY_BICYCLE = 6
exports.TRANSPORT_BY_OTHER = 7
